/*
 * hlquery - Search beyond keywords.
 * http://www.hlquery.com
 *
 * Copyright (C) 2021-2026, Carlos F. Ferry <carlos.ferry@gmail.com>
 *
 * This file is part of hlquery, released under the BSD License version 3.
 * You are free to redistribute and/or modify this software
 * under the terms of the BSD License.
 * For more details, please visit: https://docs.hlquery.com
 */

/* Generated by configure script - DO NOT EDIT MANUALLY */

#pragma once

/* Socket Engine Configuration */

#define SOCKETENGINE_NAME "${SOCKETENGINE_NAME}"

/* Build Information */

#define HLQUERY_VERSION "${HLQUERY_VERSION}"
#define HLQUERY_SYSTEM "${HLQUERY_SYSTEM}"

/* Installation paths */

#define HLQUERY_CONFIG_DIR "${HLQUERY_CONFIG_DIR}"
#define HLQUERY_DATA_DIR "${HLQUERY_DATA_DIR}"
#define HLQUERY_LOG_DIR "${HLQUERY_LOG_DIR}"
#define HLQUERY_ADMIN_DIR "${HLQUERY_ADMIN_DIR}"
#define HLQUERY_PID_DIR "${HLQUERY_PID_DIR}"
#define HLQUERY_SSL_DIR "${HLQUERY_SSL_DIR}"
#define HLQUERY_MODULE_DIR "${HLQUERY_MODULE_DIR}"

/* Networking defaults */

#define HLQUERY_DEFAULT_HTTP_PORT ${HLQUERY_DEFAULT_HTTP_PORT}

/* Feature flags */

${HLQUERY_HAS_THREADS}
${HLQUERY_SSL_DEFINES}

/* Shared library export/import helpers */

#if defined(__GNUC__) || defined(__clang__)
# define CoreExport __attribute__((visibility("default")))
#else
# define CoreExport
#endif

/* Threading Configuration */

#define HLQUERY_MAX_THREADS ${HLQUERY_MAX_THREADS}

/* Connection limits and throttling */
/* Maximum concurrent connections (increased for benchmarking) */

#define MAX_CONNECTIONS 1000

/* Maximum queued connections (increased for benchmarking) */

#define MAX_PENDING_CONNECTIONS 100

/* User timeout configuration */
/* User timeout in seconds - more aggressive for dead connections */

#define TIMEOUT_SECONDS 30

/* LSM Storage Engine - High-Performance Custom Implementation */

#define HLQ_LSM_ENABLED ${HLQ_LSM_ENABLED}

/* Performance and Processing Configuration */
/* Maximum connections processed per tick (increased for benchmarking) */

#define MAX_PROCESS_PER_TICK 10

/* Maximum connections accepted per tick (increased for benchmarking) */

#define MAX_CONNECTIONS_PER_TICK 10

/* Circuit Breaker and Error Handling Configuration */
/* Maximum consecutive errors before circuit breaker triggers */

#define MAX_CONSECUTIVE_ERRORS 100

/* Circuit breaker timeout in seconds (reduced for faster recovery) */

#define CIRCUIT_BREAKER_TIMEOUT 15

/* Dictionary Configuration */

#define DICT_OK 0
#define DICT_ERR 1

/* QuickList Configuration */

#define QUICKLIST_HEAD 0
#define QUICKLIST_TAIL -1
#define QUICKLIST_NOCOMPRESS 0

/* QuickList Node Encoding */

#define QUICKLIST_NODE_ENCODING_RAW 1
#define QUICKLIST_NODE_ENCODING_LZF 2

/* QuickList Node Container */

#define QUICKLIST_NODE_CONTAINER_PLAIN 1
#define QUICKLIST_NODE_CONTAINER_PACKED 2

/* QuickList Start Position */

#define AL_START_HEAD 0
#define AL_START_TAIL 1

/* Lock-Free Structures Configuration */
/* Maximum level for skip lists and other hierarchical structures */

#define MAX_LEVEL 16

/* HTTP Server Configuration */
/* Maximum requests per HTTP connection (keep-alive limit) */

#define HTTP_MAX_REQUESTS_PER_CONNECTION 100

/* HTTP keep-alive timeout in seconds */

#define HTTP_KEEP_ALIVE_TIMEOUT_SEC 30

/* HTTP connection timeout in seconds (Slowloris protection) */

#define HTTP_CONNECTION_TIMEOUT_SECONDS 60

/* Maximum HTTP request size in bytes (100MB) */

#define HTTP_MAX_REQUEST_SIZE (100 * 1024 * 1024)

/* Maximum HTTP response size in bytes (100MB) */

#define HTTP_MAX_RESPONSE_SIZE (100 * 1024 * 1024)

/* Maximum URL decoded size in bytes (10MB) */

#define HTTP_MAX_DECODED_SIZE (10 * 1024 * 1024)

/* Maximum HTTP connections accepted per tick */

#define HTTP_MAX_ACCEPTS_PER_TICK 10

/* Action List Configuration */
/* Maximum number of actions that can be queued (prevents unbounded growth) */

#define MAX_QUEUE_SIZE 10000

/* Initial capacity for vectors to reduce reallocations */

#define INITIAL_CAPACITY 64

/* Initializer Configuration Constants */
/* DNS cache flush interval in seconds (1 hour) */

#define DNS_CACHE_FLUSH_INTERVAL_SEC 3600

/* DNS cache max entries (forward + reverse). Default: 1024 */

#define DNS_CACHE_MAX_SIZE 1024

/* Metadata scan maximum wait time in seconds (5 minutes) */

#define METADATA_SCAN_MAX_WAIT_SECONDS 300

/* Metadata scan sleep interval in milliseconds */

#define METADATA_SCAN_SLEEP_MS 100

/* Daemon Configuration Constants */
/* Default shutdown timeout in seconds (small/empty database) */

#define DAEMON_SHUTDOWN_TIMEOUT_SEC 10

/* Extended shutdown timeout in seconds (normal database with active data) */

#define DAEMON_SHUTDOWN_TIMEOUT_EXTENDED_SEC 30

/* LSM Engine Configuration Constants */
/* Maximum WAL entry size in bytes (1MB) */

#define MAX_WAL_ENTRY_SIZE (1024 * 1024)

/* Maximum WAL entry size during recovery in bytes (100MB) - allows larger entries during recovery */

#define MAX_WAL_ENTRY_SIZE_RECOVERY (100 * 1024 * 1024)

/* TODO 5: Unified check: use MAX_WAL_ENTRY_SIZE for normal writes, MAX_WAL_ENTRY_SIZE_RECOVERY for recovery */

#define MAX_WAL_ENTRY_SIZE_FOR_MODE(is_recovery) ((is_recovery) ? MAX_WAL_ENTRY_SIZE_RECOVERY : MAX_WAL_ENTRY_SIZE)

/* Maximum value length in WAL recovery in bytes (100MB) */

#define MAX_WAL_VALUE_LENGTH_RECOVERY (100 * 1024 * 1024)

/* Maximum hot data entries per shard */

#define LSM_MAX_HOT_DATA_SIZE 10000

/* Maximum wait count for thread shutdown (100ms max) */

#define LSM_MAX_WAIT_COUNT 10

/* 
 * Memtable flush threshold (entries)
 * Increased from 1000 to 10000 to reduce excessive small SSTables and compaction overhead.
 * This improves write throughput and reduces random reads by creating larger SSTables.
 */

#define LSM_MEMTABLE_FLUSH_THRESHOLD 10000

/* Number of sharded mutexes for hot paths */

#define LSM_SHARDED_MUTEXES 16

/* Hybrid Storage Configuration Constants */
/* Number of mutexes for collection locking */

#define HYBRID_STORAGE_NUM_MUTEXES 16

/* Flush threshold: number of documents before flush (only flush when memtable is full) */
/* Flush occurs when memtable is full or after time interval */

#define HYBRID_STORAGE_FLUSH_DOC_COUNT 10000  // Increased from 100 to 10000 - only flush when memtable is full

/* Flush threshold: time interval in seconds before flush (30s default) */

#define HYBRID_STORAGE_FLUSH_INTERVAL_SEC 30  // Increased from 5 to 30 seconds

/* Maximum segments per collection */

#define HYBRID_STORAGE_MAX_SEGMENTS 1000

/* Batch size for key deletion operations */

#define HYBRID_STORAGE_DELETE_BATCH_SIZE 1000

/* Maximum initial load documents (on-demand loading) */

#define HYBRID_STORAGE_MAX_INITIAL_LOAD 50

/* Batch size for document processing */

#define HYBRID_STORAGE_BATCH_SIZE 25

/* Document Storage Configuration Constants */
/* Maximum segment size in bytes (10MB per segment) */

#define DOCUMENT_STORAGE_MAX_SEGMENT_SIZE (10 * 1024 * 1024)

/* Maximum segments per collection */

#define DOCUMENT_STORAGE_MAX_SEGMENTS 1000

/* SSTable Configuration Constants */
/* Block size in bytes (64KB blocks) */

#define SSTABLE_BLOCK_SIZE (64 * 1024)

/* Maximum SSTable size in bytes (10GB max) */

#define MAX_SSTABLE_SIZE (10ULL * 1024 * 1024 * 1024)

/* Inverted Index Configuration Constants */
/* Maximum active postings in RAM before sealing */

#define INVERTED_INDEX_MAX_ACTIVE_POSTINGS 100000

/* Maximum wildcard terms per query */

#define INVERTED_INDEX_MAX_WILDCARD_TERMS 1000

/* Snippet window size in tokens */

#define INVERTED_INDEX_SNIPPET_WINDOW 12

/* Maximum documents to process in search */

#define INVERTED_INDEX_MAX_DOCUMENTS_TO_PROCESS 1000000

/* Early termination factor (stop if processed 10x top_k) */

#define INVERTED_INDEX_EARLY_TERMINATION_FACTOR 10

/* Maximum vector dimension */

#define INVERTED_INDEX_MAX_VECTOR_DIMENSION 100000

/* Epsilon for floating point comparisons */

#define INVERTED_INDEX_EPSILON 1e-6f

/* Maximum memory for inverted index (2GB) */

#define INVERTED_INDEX_MAX_MEMORY_BYTES (2ULL * 1024 * 1024 * 1024)

/* Maximum terms per collection (10M) */

#define INVERTED_INDEX_MAX_TERMS_PER_COLLECTION 10000000

/* Maximum documents per collection (5M) */

#define INVERTED_INDEX_MAX_DOCUMENTS_PER_COLLECTION 5000000

/* Memory check interval (check every 1000 documents) */

#define INVERTED_INDEX_MEMORY_CHECK_INTERVAL 1000

/* Config Reader Configuration Constants */
/* Maximum config file size in bytes (10MB) */

#define CONFIG_READER_MAX_CONFIG_SIZE (10 * 1024 * 1024)
/* Maximum tags in config file */

#define CONFIG_READER_MAX_TAGS 10000

/* Maximum attributes per tag */

#define CONFIG_READER_MAX_ATTRIBUTES 100

/* Maximum attribute length in bytes (64KB) */

#define CONFIG_READER_MAX_ATTR_LENGTH 65536

/* Maximum include depth (prevent infinite recursion) */

#define CONFIG_READER_MAX_INCLUDE_DEPTH 10

/* Maximum include file size in bytes (5MB per include) */

#define CONFIG_READER_MAX_INCLUDE_SIZE (5 * 1024 * 1024)

/* Database Configuration Constants */
/* Maximum key size in bytes (1MB max key size) */

#define DATABASE_MAX_KEY_SIZE (1024 * 1024)

/* Memory Safety Configuration Constants */
/* Maximum string size in bytes (1MB max) */

#define MEMORY_SAFETY_MAX_STRING_SIZE (1024 * 1024)

/* Backup/Restore Configuration Constants */
/* Chunk size for backup/restore operations in bytes (64KB chunks) */

#define BACKUP_RESTORE_CHUNK_SIZE (64 * 1024)

/* Memtable Configuration Constants */
/* Maximum retries for memtable operations */

#define MEMTABLE_MAX_RETRIES 10

/* Search API Configuration Constants */
/* Maximum errors before giving up */

#define SEARCH_API_MAX_ERRORS 10
/* Maximum documents to process in search (1M document limit) */

#define SEARCH_API_MAX_DOCUMENTS_TO_PROCESS 1000000

/* Epsilon for floating point comparisons */

#define SEARCH_API_EPSILON 1e-6f

/* Maximum matches per word (prevent infinite loop) */

#define SEARCH_API_MAX_MATCHES_PER_WORD 100

/* Earth's radius in kilometers (for geosearch) */

#define SEARCH_API_EARTH_RADIUS_KM 6371.0

/* Replication Protocol Configuration Constants */
/* Batch size for replication operations */

#define REPLICATION_PROTOCOL_BATCH_SIZE 1000

/* Socket Engine Configuration Constants */
/* Epoll batch size for high-speed writes */

#define EPOLL_BATCH_SIZE 64

/* Poll batch size */

#define POLL_BATCH_SIZE 1

/* HTTP Server Buffer Configuration Constants */
/* HTTP read buffer size in bytes (increased from 4096) */

#define HTTP_READ_BUFFER_SIZE 8192

/* RocksDB Default Configuration Constants */
/* Create database if missing */

#define ROCKSDB_DEFAULT_CREATE_IF_MISSING 1

/* Create missing column families */

#define ROCKSDB_DEFAULT_CREATE_MISSING_COLUMN_FAMILIES 1

/* Error if database exists */

#define ROCKSDB_DEFAULT_ERROR_IF_EXISTS 0

/* Maximum background jobs */

#define ROCKSDB_DEFAULT_MAX_BACKGROUND_JOBS 4

/* Write buffer size in bytes (64MB) */

#define ROCKSDB_DEFAULT_WRITE_BUFFER_SIZE (64 * 1024 * 1024)
/* Maximum write buffer number */

#define ROCKSDB_DEFAULT_MAX_WRITE_BUFFER_NUMBER 3

/* Target file size base in bytes (64MB) */

#define ROCKSDB_DEFAULT_TARGET_FILE_SIZE_BASE (64 * 1024 * 1024)

/* Maximum bytes for level base in bytes (256MB) */

#define ROCKSDB_DEFAULT_MAX_BYTES_FOR_LEVEL_BASE (256 * 1024 * 1024)
