name: FreeBSD Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v1.3.0
        with:
          operating_system: freebsd
          version: '14.4'
          shell: sh
          memory: 6G
          cpu_count: 3
          run: |
            sudo env IGNORE_OSVERSION=yes ASSUME_ALWAYS_YES=yes pkg update -f
            sudo env IGNORE_OSVERSION=yes ASSUME_ALWAYS_YES=yes pkg install -y cmake gmake perl5 pkgconf openssl
            ./configure --skip-tests
            gmake
